version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app-php
    image: dev/php
    working_dir: /var/www/html/projetos/microservice-catalogo-video
    volumes:
      - ./:/var/www/html/projetos/microservice-catalogo-video
    networks:
      - app-php

  nginx:
    image: nginx:latest
    container_name: app-nginx
    ports:
      - 8888:80
    volumes:
      - ./:/var/www/html/projetos/microservice-catalogo-video
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-php

networks:
  app-php:
    driver: bridge
